/**
 * Expo config plugin — wires Stella's CarPlay scene into the iOS project.
 *
 * This is a Continuous Native Generation (CNG) app: `ios/` is gitignored and
 * regenerated by `expo prebuild` (and by EAS Build), so all native CarPlay
 * wiring lives here rather than in a hand-edited Xcode project.
 *
 * What it does:
 *   1. Declares a CarPlay template scene in `UIApplicationSceneManifest`. Only
 *      the CarPlay scene role is declared, so the phone UI keeps using the
 *      Expo AppDelegate's window (no risky full scene migration of the phone
 *      app — this is the proven react-native-carplay pattern).
 *   2. Writes an Objective-C `StellaCarSceneDelegate` that hands the CarPlay
 *      interface controller to react-native-carplay's `RNCarPlay`, so the JS
 *      template controller (src/carplay) takes over on connect.
 *   3. Registers that delegate's `.m` in the Xcode project's Sources phase.
 *
 * Entitlement (NOT added here — see CARPLAY.md): a real CarPlay head unit
 * requires Apple to grant `com.apple.developer.carplay-audio` (Audio category).
 * Adding it before Apple grants it breaks device code-signing, so it is left
 * out; the iOS CarPlay Simulator does not enforce entitlements, so the build
 * runs there without it.
 */

const {
  withInfoPlist,
  withDangerousMod,
  withXcodeProject,
  IOSConfig,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const DELEGATE = "StellaCarSceneDelegate";
const SCENE_CONFIG_NAME = "Stella-CarPlay";

const HEADER_CONTENTS = `// Generated by plugins/withStellaCarPlay.js — do not edit by hand.
#import <UIKit/UIKit.h>
#import <CarPlay/CarPlay.h>

@interface ${DELEGATE} : UIResponder <CPTemplateApplicationSceneDelegate>
@end
`;

const IMPL_CONTENTS = `// Generated by plugins/withStellaCarPlay.js — do not edit by hand.
#import "${DELEGATE}.h"
#import "RNCarPlay.h"

@implementation ${DELEGATE}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
   didConnectInterfaceController:(CPInterfaceController *)interfaceController
                        toWindow:(CPWindow *)window {
  [RNCarPlay connectWithInterfaceController:interfaceController window:window];
}

- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene
didDisconnectInterfaceController:(CPInterfaceController *)interfaceController
                      fromWindow:(CPWindow *)window {
  [RNCarPlay disconnect];
}

@end
`;

const withCarPlaySceneManifest = (config) =>
  withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: true,
      UISceneConfigurations: {
        CPTemplateApplicationSceneSessionRoleApplication: [
          {
            UISceneClassName: "CPTemplateApplicationScene",
            UISceneConfigurationName: SCENE_CONFIG_NAME,
            UISceneDelegateClassName: DELEGATE,
          },
        ],
      },
    };
    return cfg;
  });

const withCarSceneDelegateSource = (config) =>
  withDangerousMod(config, [
    "ios",
    (cfg) => {
      const appName = cfg.modRequest.projectName;
      const dir = path.join(cfg.modRequest.platformProjectRoot, appName);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${DELEGATE}.h`), HEADER_CONTENTS);
      fs.writeFileSync(path.join(dir, `${DELEGATE}.m`), IMPL_CONTENTS);
      return cfg;
    },
  ]);

const withCarSceneDelegateBuildFile = (config) =>
  withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const appName = cfg.modRequest.projectName;
    const relPath = `${appName}/${DELEGATE}.m`;
    // Idempotent: prebuild may run twice against the same project.
    if (!project.hasFile(relPath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: relPath,
        groupName: appName,
        project,
      });
    }
    return cfg;
  });

/** @param {import('@expo/config-plugins').ExpoConfig} config */
module.exports = function withStellaCarPlay(config) {
  config = withCarPlaySceneManifest(config);
  config = withCarSceneDelegateSource(config);
  config = withCarSceneDelegateBuildFile(config);
  return config;
};
